In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
# define vocabulary size
voc_size = 10000


In [4]:
# one hot reprsentation
one_hot_repr=[one_hot(words , voc_size)for words in sent]
one_hot_repr
    

[[3721, 9646, 552, 9905],
 [3721, 9646, 552, 9333],
 [3721, 8662, 552, 1899],
 [3195, 2747, 4479, 318, 9609],
 [3195, 2747, 4479, 318, 9220],
 [8202, 3721, 1336, 552, 2897],
 [5308, 8087, 5276, 318]]

In [5]:
# word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [6]:
import numpy as np

In [19]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding = "pre" , maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3721, 9646,  552, 9905],
       [   0,    0,    0,    0, 3721, 9646,  552, 9333],
       [   0,    0,    0,    0, 3721, 8662,  552, 1899],
       [   0,    0,    0, 3195, 2747, 4479,  318, 9609],
       [   0,    0,    0, 3195, 2747, 4479,  318, 9220],
       [   0,    0,    0, 8202, 3721, 1336,  552, 2897],
       [   0,    0,    0,    0, 5308, 8087, 5276,  318]])

In [20]:
# feaature reprsentation
dim = 10

In [21]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 113ms/step


array([[[ 0.00363641,  0.03509611, -0.0082149 , -0.01953466,
         -0.0223231 , -0.00866718,  0.01791103, -0.02100034,
         -0.03772565, -0.00372071],
        [ 0.00363641,  0.03509611, -0.0082149 , -0.01953466,
         -0.0223231 , -0.00866718,  0.01791103, -0.02100034,
         -0.03772565, -0.00372071],
        [ 0.00363641,  0.03509611, -0.0082149 , -0.01953466,
         -0.0223231 , -0.00866718,  0.01791103, -0.02100034,
         -0.03772565, -0.00372071],
        [ 0.00363641,  0.03509611, -0.0082149 , -0.01953466,
         -0.0223231 , -0.00866718,  0.01791103, -0.02100034,
         -0.03772565, -0.00372071],
        [ 0.02212942,  0.0299913 , -0.03651942,  0.02228015,
          0.02301599, -0.03891807, -0.04334856,  0.04990189,
         -0.01260747,  0.04605223],
        [ 0.02590254, -0.04218359, -0.04122535,  0.04991739,
         -0.02210764,  0.01055779, -0.01377866,  0.02557613,
          0.01457374, -0.01575459],
        [-0.04775996, -0.03147574,  0.00098864, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 3721, 9646,  552, 9905])